sudo: required

language: ruby

services:
  - docker
  
before_install:
  - docker pull graemeastewart/hsf-jekyll
 
 # Change ownership of the checkout to match the jekyll user in the container
install:
  - sudo chown -R 1000:1000 .

script:
  - docker run --volume $(pwd):/srv/jekyll --interactive --tty graemeastewart/hsf-jekyll /bin/sh -c /srv/jekyll/.travis-scripts/html-proofer

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
