sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull hepsoftwarefoundation/hsf-jekyll

 # Skip install as the container does all the work
install: /bin/true

script:
  - docker run --volume $(pwd):/srv/jekyll --interactive --tty --user $(id -u) --env HOME=/tmp hepsoftwarefoundation/hsf-jekyll /bin/sh -c /srv/jekyll/.travis-scripts/html-proofer

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
