- title: Thematic CERN School of Computing 2020
  source: https://indico.cern.ch/event/861566/program
  date: 2020-06-07
  end_date: 2020-06-13
  author: Guillermo Fidalgo
  layout: event
  categories: Schools
  deadline: 27 February 2020
- title: AEPSHEP (Asia-Europe-Pacific School of High-Energy Physics)
  source: http://2018.aepshep.org/
  date: 2018-09-12
  end_date: 2018-09-25
  author: Guillermo Fidalgo
  layout: event
  categories: Schools
-
